URL_WEBPAGE = "https://inspirehep.net/"
URL_AUTHORS = URL_WEBPAGE + "authors/"
URL_INSTITUTIONS = URL_WEBPAGE + "institutions/"
URL_LITERATURE =  URL_WEBPAGE + "literature/"
URL_JOBS = URL_WEBPAGE + "jobs/"
URL_SEMINARS = URL_WEBPAGE + "seminars/"
URL_CONFERENCES = URL_WEBPAGE + "conferences/"
